---
- name: NFS Client
  become_user: root
  become: yes
  hosts: 192.168.122.112

  tasks:
  - name: Installing NFS
    yum:
      name: nfs-utils
      state: latest
  - name: Create a mountpoint for NFS
    file:
      path: /nfsmount
      state: directory
      mode: 755
      owner: root

  - name: update fstab and mount nfs share
    mount:
      name: /nfsmount
      src: 192.168.122.111:/nfsshare
      fstype: nfs
      opts: defaults,rw
      dump: 0
      passno: 0 
      state: mounted
 


