---
- name: NFS
  become_user: root
  become: yes
  hosts: localhost

  vars:
    nfs_mountpoint: '/nfsmount'
    nfsserver: '192.168.122.111'
    fsexport: '/nfsshare'
  tasks:
  - name: Installing NFS
    yum:
      name: nfs-utils
      state: latest
  - name: Enabling the service
    service:
      name: nfs
      enabled: yes
  - name: Starting the service
    service:
      name: nfs
      state: started
  - name: Adding smtp in firewall
    firewalld:
      zone: public
      service: nfs
      permanent: yes
      state: enabled
  - name: Create a mountpoint for NFS
    file:
      path: {{ nfs_mountpoint }}
      state: directory
      mode: 755
      owner: root
    tags: nfs_client

  - name: update fstab and mount nfs share
    mount:
      name: {{ nfs_mountpoint }}
      src: {{ nfsserver }}:/{{ nfsexport }}
      fstype: nfs
      opts: defaults,rw,bg
      dump: 0
      passsno: 2 
      state: mounted
    tags: nfs_client


