---
- name: NFS
  become_user: root
  become: yes
  hosts: localhost
  tasks:
  - name: Installing NFS
    yum:
      name: nfs-utils
      state: latest
  - name: Enabling the service
    service:
      name: nfs-server
      enabled: yes
  - name: Starting the service
    service:
      name: nfs-server
      state: started
  - name: Adding smtp in firewall
    firewalld:
      zone: public
      service: nfs
      permanent: yes
      state: enabled
  - name: copy /etc/exports
    template:
      src=exports.j2
      dest=/etc/exports
      owner=root
      group=root
      mode=755
    tags: nfs_server,nfs_client

  



