---
- name: NFS Server
  become_user: root
  become: yes
  hosts: nfs_server
  tasks:
  - name: Installing NFS
    yum:
      name: nfs-utils
      state: latest
  - name: Enabling the NFS service
    service:
      name: nfs-server
      enabled: yes
  - name: Starting the NFS service
    service:
      name: nfs-server
      state: started
  - name: Adding NFS in firewall
    firewalld:
      zone: public
      service: nfs
      immediate: yes
      state: enabled
  - name: Creating NFS share
    file: 
      path: /nfsshare
      state: directory
  - name: copy /etc/exports
    template:
      src=exports.j2
      dest=/etc/exports
      owner=root
      group=root
      mode=755
  - name: Exporting Share
    raw: exportfs -r
  



